# Generated by Django 5.1.4 on 2024-12-09 16:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('time', models.DateField(verbose_name=django.utils.timezone.now)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
