# Generated by Django 5.1.4 on 2024-12-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_alter_album_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='album',
            name='name',
            field=models.CharField(default='默认相册', max_length=50),
        ),
    ]
