# Generated by Django 5.1.4 on 2024-12-09 16:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('album', '0001_initial'),
        ('moment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateField(default=django.utils.timezone.now)),
                ('file_name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('creator', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Picture_Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moved_time', models.DateTimeField(auto_now_add=True)),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.album')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picture.picture')),
            ],
            options={
                'unique_together': {('pid', 'aid')},
            },
        ),
        migrations.CreateModel(
            name='Picture_Moment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moment.moment')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picture.picture')),
            ],
            options={
                'unique_together': {('pid', 'mid')},
            },
        ),
    ]
