# Generated by Django 5.1.4 on 2024-12-09 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trip', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trip.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Moment_Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('like', models.BooleanField(null=True)),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moment.moment')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('content__isnull', True), _negated=True), models.Q(('like__isnull', True), _negated=True), _connector='OR'), name='check_like_or_content_not_null')],
                'unique_together': {('pid', 'mid')},
            },
        ),
    ]
