# Generated by Django 5.1.4 on 2024-12-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='discover',
            field=models.ImageField(null=True, upload_to='discover/'),
        ),
    ]
