# Generated by Django 5.1.4 on 2024-12-11 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0003_moment_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moment',
            old_name='text',
            new_name='content',
        ),
        migrations.AddField(
            model_name='moment',
            name='aid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='moment.moment'),
        ),
    ]
