# Generated by Django 5.1.4 on 2024-12-11 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_album_cover_url_album_name'),
        ('moment', '0004_rename_text_moment_content_moment_aid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='aid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='album.album'),
        ),
    ]
