# Generated by Django 5.1.4 on 2024-12-09 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trip', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateField()),
                ('place', models.TextField()),
                ('description', models.TextField()),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.trip')),
            ],
        ),
    ]
