# Generated by Django 5.1.4 on 2024-12-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='title',
            field=models.CharField(default='default_title', max_length=255),
            preserve_default=False,
        ),
    ]
