# Generated by Django 5.1.4 on 2024-12-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_person_default_aid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='avatar',
        ),
        migrations.AddField(
            model_name='person',
            name='avatar_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
