# Generated by Django 5.1.4 on 2024-12-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='time',
            new_name='stime',
        ),
        migrations.AddField(
            model_name='trip',
            name='ttime',
            field=models.DateTimeField(default='2024-12-10 15:13'),
            preserve_default=False,
        ),
    ]
