# Generated by Django 5.1.4 on 2024-12-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_rename_time_trip_stime_trip_ttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='stime',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='ttime',
            field=models.DateField(),
        ),
    ]
